version: 3

tasks:
  install:
    cmds:
      - go install github.com/apigear-io/cli/cmd/apigear@latest
  clean:
    cmds:
      - cmd: powershell del -r -fo test
        platforms: [windows]
        ignore_error: true
      - cmd: rm -rf test
        platforms: [linux, darwin]
        ignore_error: true
  test:
    cmds:
      - task: clean
      - apigear g s ./apigear/goldenmaster.solution.yaml

  py::install:
    desc: install the dependencies
    dir: test
    cmds:
      - pip install -r requirements.txt  
  pytest:
    desc: runs pytest in test dir
    dir: test
    cmds:      
      - pytest
  diff:
    cmds:
      - git --no-pager diff --no-index ./goldenmaster ./test
