version: 3

vars:
  BIN: apigear{{exeExt}}
tasks:
  install:
    cmds:
      - go install github.com/apigear-io/cli/cmd/apigear@latest
      - pip install black
      # - rm -rf tmp bin
      # - mkdir tmp bin
      # - gh release download --repo apigear-io/cli --pattern "apigear_{{OS}}_{{ARCH}}.zip" --dir tmp
      # - unzip tmp/apigear_{{OS}}_{{ARCH}}.zip -d bin
  clean:
    cmds:
      - cmd: powershell Remove-Item -Recurse -Force test
        platforms: [windows]
        ignore_error: true
      - cmd: rm -rf test bin tmp
        platforms: [linux, darwin]
        ignore_error: true
  test:
    cmds:
      - task: clean
      - "{{.BIN}} g s ./apigear/goldenmaster.solution.yaml"

  py:install:
    desc: install the dependencies
    dir: test
    cmds:
      - pip install -r requirements.txt
  py:test:
    desc: runs pytest in test dir
    dir: test
    cmds:
      - pytest
  diff:
    cmds:
      - git --no-pager diff --no-index ./goldenmaster ./test
  format:
    dir: test
    cmds:
      - black .
  ci:
    desc: runs the ci pipeline
    cmds:
      - task: install
      - task: test
      - task: diff
      - task: py:install
      - task: py:test
