# This workflow will ensure that the goldenmaster is always up-to-date before being merged

name: Technology Template Goldenmaster Test

on:
  pull_request:
    branches: [main]

env:
  GITHUB_AUTH_TOKEN: ${{ secrets.WOLFGANG_REPO_PACKAGE_READ }}
  GOPRIVATE: "github.com/apigear-io/*"
  GH_ACCESS_TOKEN: ${{ secrets.APIGEAR_REPOS }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  go_version: "1.20.x"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-go@v3
        with:
          go-version: ${{env.go_version}}
      - uses: arduino/setup-task@v1
      - run: task install
      - run: task test
      - run: task diff
      - run: task py:install
      - run: task py:test
