# This workflow ensures that the goldenmaster is up to date with the templates
# (i.e. that templates/ regenerated against the test-apis matches goldenmaster/).

name: Technology Template Goldenmaster Test

on:
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  go_version: "1.21.x"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - uses: arduino/setup-task@v2
      - run: task install
      - run: task generate_solution
      - run: task diff
